language: csharp
solution: libvt100.sln

jobs:
  include:
    - dotnet: 3.1
      mono: none
      env: DOTNETCORE=3  # optional, can be used to take different code paths in your script
    - mono: latest
    